### ISSUE TITLE
Completing report

### ISSUE THREAD

**Issue by abyot** [abyot/sun-inventory#103] opened 2016-12-20 09:29 UTC
Hi @chloedenavit @Alisia1,

Completing reports from the summary report page has become almost impossible. 

The thing is that in the summary report we have a mix of actions and their different instances. However, our completeness works for a unique combination of action and instance. Given such completeness model, it is very likely we are going to have a mix of completed and not-completed rows in the summary report. Users can go and fill a new action (or the same action with a different instance) after generating summary report (and also completing them)... challenge is kind of identify those completed and not completed... 

In the summary report, I can add one more column with checkbox (actually two columns) for users to say decide which ones to mark-(not)-complete.. this will really make it messy for users as they have to scan through the entire row of summary report and decide on the check-boxes.. 

Also to manage in the summary report is what to with the empty rows. Are we going to mark them complete? 

I am suggesting for a simpler solution - add one more button "Save and complete" in the data entry tab. This button can do both save and complete in one click. If users are are unsure of completing, they can simply save.. and later come back and complete... 

What are your thoughts?

![image](https://cloud.githubusercontent.com/assets/4967749/21345112/22eec986-c69f-11e6-82a9-312d94527a74.png)

**Comment by chloedenavit** [comment] 2016-12-21 10:08
Hi @abyot,

I have been thinking about the last option you suggested, which makes sense, but I found one big issue with it. The issue is that users may click on "Save", and then forget to come back to "mark complete". There are so many actions that it seems very likely they will forget to mark some of them as complete. It is also a hassle for them to track down or remember which ones have not been marked, and go back to each one. 

Can we try to find another solution?

For me, the purpose of this feature is to know when one agency has finished entering data (for a country, year, agency). In fact, I am not sure it is necessary to mark individual action instances as complete or not.
Perhaps we should not be using the completeness button that DHIS2 typically uses, and instead create a different button whose only purposes are : 1) to "lock" this agency's data and 2) to send a message to the administrator that the agency is finished entering data.

Also, you said "Users can go and fill a new action after generating and completing summary report". But what if we lock the data after they have clicked on "mark complete" so that they cannot add new ones? We could also create a button for the agency to "mark not complete" if they decide they need to change something? 

Let me know your thoughts! Thank you.

**Comment by abyot** [comment] 2016-12-21 10:21
I can see your point. However, the issue is we don't have "one report", rather multiple ones. Each action by itself is a report and marking complete (not complete) is associated to this action (and its unique instance). 

We can workout on the UI, but behind the scene (the data model, notification process and the like) need to match existing DHIS2 data model.

You raised one point which could simplify things... the moment a user / agency clicked complete - we can mark whatever data the agency has entered complete. But keep in mind that, behind the scene we are completing multiple actions. From this point on, the agency can not enter/edit any data, even for those new actions. First, need to click on "mark not complete" - again behind the scene not completing each action.

**Comment by chloedenavit** [comment] 2016-12-21 10:47
Yes, it is fine to mark all of their actions as complete once they click on the button. 

You also asked about the blank rows, but I am not sure I can answer until I understand better what the implications are of marking all the blank rows complete or not complete automatically. Could you explain what the implications will be in the system, for the user, and for the reports?

**Comment by abyot** [comment] 2016-12-21 11:20
The summary report shows both filled and empty rows. 

What do you want to do with the empty rows? 

Do you want them to be marked complete or get ignored in the mark-(not)-complete process? 

Technically it is no difference. 

However, for users - someone interpreting and / or filling the data - I see a big difference. For those filling the data - it is like completing something which they haven't even seen. Users might not go through all the actions in the data entry tab. In the report tab, the system will scan through all the actions and pick everything - filled or not filled ... and blindly marking all complete I would say is dangerous. Because, for those interpreting the data, it gives a sense of "ok the agency has gone through this ... and marked complete..." which might not be true.... This was the reason where I suggested may be to have a checkbox (actually two columns)... for each action / row and decide whether to mark-(not)-complete each. This effectively means going through each action ... that is why I suggested doing this while doing the data entry itself... even better... it is possible to do both saving and completing by just clicking one button... but you said this won't work.

So the question is, what to do with the empty rows? A simpler thing to do is to ignore the empty rows during mark-(not)-complete process. 

We can do this. A strange situation, though, is imagine an agency filling just one action and clicking complete. Then things are locked.... in order to add a new action mark-not-complete needs to be clicked. See how the two tabs are kind of depending on each other ... I would be happy if we could avoid that. I have no issue, technically... it is just that users need to make the connection between the two tabs every time they are trying to enter data.

One thing I have been thinking is ... everytime they pick a new action / instance combination which is not completed ... allow them to enter data. Locking should apply only for those completed ones. The issue with this approach is that ... later when trying to mark-(not)-complete from the summary report tab, there could potentially be a mix of completed and not completed action/instances... this then puts me back to the thing mentioned earlier ... i.e. allow users to identify which ones to mark-complete which ones to mark-not-complete.

**Comment by chloedenavit** [comment] 2016-12-21 13:17
Hi @abyot,
I would be fine with ignoring the blank rows when clicking on "mark complete". 

I understand your point about not wanting users to have to navigate between the two tabs to mark complete or mark incomplete. Maybe we should go back to having the Mark complete button on the first tab, if you think that is better? 

Perhaps after clicking this button, a pop-up message can invite users to check their actions in the Summary Report before marking complete. 

Let me know if there are still issues with this that I have not answered.

**Comment by chloedenavit** [comment] 2016-12-21 13:23
Maybe we could put the button at the top so that it is clear that it is the third step after people review the Summary Report, and so that they don't accidentally click on it too early? 

![image](https://cloud.githubusercontent.com/assets/21313941/21390811/015047ce-c789-11e6-91b1-9014d922ef65.png)

**Closed** 2017-06-22 10:02 UTC
Labels: inventory
