### ISSUE TITLE
Reorganizing the Categories and the Thematic Areas

### ISSUE THREAD

**Issue by Alisia1** [abyot/sun-inventory#82] opened 2016-12-08 10:24 UTC
Hi Abyot,
as per our conversation, please find below the order in which the Categories and the Thematic Areas should appear:

**Categories** 

1. Food, Agriculture & Healthy Diets
2. Maternal and Child Care
3. Health
4. Social Protection
5. Multi-sectoral Nutrition Governance

**Thematic Areas**

Food, Agriculture & Healthy Diets:

1. Livestock and Fisheries
2. Crops/Horticulture
3. Food Processing, Fortification and Storage
4. Food Consumption Practices for Healthy Diets

Maternal and Child Care:

1. Infant and Young Child Feeding  

Health:

1. Nutrition Interventions Delivered through Reproductive and Paediatric Health Services
2. Micronutrient Supplementation
3. Management of Acute Malnutrition Nutrition-related Disease Prevention and Management
4. Water, Sanitation and Hygiene for Good Nutrition

Social Protection:

1. Social Assistance
2. Social Insurance  Labour Market Programmes  

Multi-sectoral Nutrition Governance :

1. Facilitation of Multi-sectoral Nutrition Governance

Please note that the first Category is called "Food, Agriculture & Healt**HY** Diets". Can you please turn the word HEALTH into HEALTHY?

thansk!!

**Comment by abyot** [comment] 2016-12-10 13:59
Duplicate of #69

**Closed by abyot** 2016-12-10 13:59 UTC
Labels: inventory
